### ISSUE TITLE
Runtime error:  'gtk-floppy' not present in theme Adwaita (0)

### ISSUE THREAD

**Issue by 9898287** [gort818/ddgtk#3]
```$ ddgtk
Traceback (most recent call last):
  File "/usr/local/bin/ddgtk", line 41, in <module>
    sys.exit(main.main())
  File "/usr/local/share/ddgtk/ddgtk/main.py", line 157, in main
    Application()
  File "/usr/local/share/ddgtk/ddgtk/main.py", line 53, in __init__
    self.icon = icontheme.load_icon(Gtk.STOCK_FLOPPY, 128, 0)
gi.repository.GLib.Error: gtk-icon-theme-error-quark: Icon 'gtk-floppy' not present in theme Adwaita (0)
```

**Comment by gort818** [comment]
Seems that Gtk.STOCK_FLOPPY has been deprecated for a while, will get this sorted out shortly, thanks for opening an issue!

**Comment by gort818** [comment]
Ok should be fixed

**Comment by metaleap** [comment]
That fix never made it into a "Release" here, right? The last being from 2017..

(I know from local running here that it also never made it into voidlinux.org/packages but that's of course not _this_ repo's responsibility =)
